### PR TITLE
use the latest st2apidocgen module

### PR DESCRIPTION
**Pull request by Sheshagiri**
Use the latest  st2apidocgen npm module. Also has some updates to circleci build. 

This https://github.com/StackStorm/st2apidocgen/pull/9 should be merged to master first.

### CODE REVIEW

**Comment by Sheshagiri** [comment]
this now fails with a different error when compared to the original one mentioned in #9 however it works fine on a nodejs:10 container on my dev setup.
```
 <<< Bundling app.js
 <<< Bundling style.css
(node:158) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/st2apidocgen/lib/survey.js:9:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:158) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:158) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  >>> Done bundling app.js [80b93528b2c0073811f77e1a6d1f88db3901e9458b063ea89d503474cf5a7320]
  >>> Done bundling style.css [79c1c26ab08129b28cd0952aed84586e102d4c584a1299e62a9ae145e6d76de6]
 ```
<details><summary>works fine on local setup</summary>

```
root@9d3b6a92cf69:/home# node -v
v10.21.0
root@9d3b6a92cf69:/home# st2apidocgen --render --output
  <<< Bundling app.js
  <<< Bundling style.css
  <<< Writing build/favicon-16x16.png
  <<< Writing build/favicon-32x32.png
  <<< Writing build/favicon-96x96.png
  <<< Writing build/openapi.yaml
  >>> Done bundling app.js [84dc8c61123854f19b43028ca0060b776016c47beda79dcdc692d8e5148e58ac]
  >>> Done bundling style.css [348d7b468fffc676817583c72f3e971ae78a45eddbcfebb3a9882b6bbf1d6730]
  <<< Rendering /
  <<< Rendering /api/v1/
  <<< Rendering /api/v1/actions
  <<< Rendering /api/v1/actionalias
  <<< Rendering /api/v1/aliasexecution
  <<< Rendering /api/v1/executions
  <<< Rendering /api/v1/keys
  <<< Rendering /api/v1/packs
  <<< Rendering /api/v1/configs
  <<< Rendering /api/v1/config_schemas
  <<< Rendering /api/v1/policytypes
  <<< Rendering /api/v1/policies
  <<< Rendering /api/v1/rbac
  <<< Rendering /api/v1/rules
  <<< Rendering /api/v1/ruletypes
  <<< Rendering /api/v1/runnertypes
  <<< Rendering /api/v1/sensortypes
  <<< Rendering /api/v1/apikeys
  <<< Rendering /api/v1/ruleenforcements
  <<< Rendering /api/v1/timers
  <<< Rendering /api/v1/traces
  <<< Rendering /api/v1/triggertypes
  <<< Rendering /api/v1/triggers
  <<< Rendering /api/v1/triggerinstances
  <<< Rendering /api/v1/webhooks
  <<< Rendering /api/exp/validation
  <<< Rendering /auth/v1/tokens
  <<< Rendering /stream/v1/stream
  <<< Writing build/app.js
  <<< Writing build/app.js.map
  <<< Writing build/style.css
  <<< Writing build/style.css.map
  >>> Done rendering /
  >>> Done rendering /api/v1/
  >>> Done rendering /api/v1/actions
  >>> Done rendering /api/v1/actionalias
  >>> Done rendering /api/v1/aliasexecution
  >>> Done rendering /api/v1/executions
  >>> Done rendering /api/v1/keys
  >>> Done rendering /api/v1/packs
  >>> Done rendering /api/v1/configs
  >>> Done rendering /api/v1/config_schemas
  >>> Done rendering /api/v1/policytypes
  >>> Done rendering /api/v1/policies
  >>> Done rendering /api/v1/rbac
  >>> Done rendering /api/v1/rules
  >>> Done rendering /api/v1/ruletypes
  >>> Done rendering /api/v1/runnertypes
  >>> Done rendering /api/v1/sensortypes
  >>> Done rendering /api/v1/apikeys
  >>> Done rendering /api/v1/ruleenforcements
  >>> Done rendering /api/v1/timers
  >>> Done rendering /api/v1/traces
  >>> Done rendering /api/v1/triggertypes
  >>> Done rendering /api/v1/triggers
  >>> Done rendering /api/v1/triggerinstances
  >>> Done rendering /api/v1/webhooks
  >>> Done rendering /api/exp/validation
  >>> Done rendering /auth/v1/tokens
  >>> Done rendering /stream/v1/stream
  <<< Writing build/index.html
  <<< Writing build/api/v1/index.html
  <<< Writing build/api/v1/actions/index.html
  <<< Writing build/api/v1/actionalias/index.html
  <<< Writing build/api/v1/aliasexecution/index.html
  <<< Writing build/api/v1/executions/index.html
  <<< Writing build/api/v1/keys/index.html
  <<< Writing build/api/v1/packs/index.html
  <<< Writing build/api/v1/configs/index.html
  <<< Writing build/api/v1/config_schemas/index.html
  <<< Writing build/api/v1/policytypes/index.html
  <<< Writing build/api/v1/policies/index.html
  <<< Writing build/api/v1/rbac/index.html
  <<< Writing build/api/v1/rules/index.html
  <<< Writing build/api/v1/ruletypes/index.html
  <<< Writing build/api/v1/runnertypes/index.html
  <<< Writing build/api/v1/sensortypes/index.html
  <<< Writing build/api/v1/apikeys/index.html
  <<< Writing build/api/v1/ruleenforcements/index.html
  <<< Writing build/api/v1/timers/index.html
  <<< Writing build/api/v1/traces/index.html
  <<< Writing build/api/v1/triggertypes/index.html
  <<< Writing build/api/v1/triggers/index.html
  <<< Writing build/api/v1/triggerinstances/index.html
  <<< Writing build/api/v1/webhooks/index.html
  <<< Writing build/api/exp/validation/index.html
  <<< Writing build/auth/v1/tokens/index.html
  <<< Writing build/stream/v1/stream/index.html
root@9d3b6a92cf69:/home#
```

<details>

needs some more investigation, I'll dig into this over the weekend :)

**Comment by armab** [comment]
Maybe switching the Docker container in CircleCI to a different one may help?
There are different OS distros in https://hub.docker.com/_/node/

**Comment by Sheshagiri** [comment]
@armab I finally found that the build issue was because the project level environment variables(`ST2_BRANCH` and other) are not available to the builds happening from forks. I'll connect with you on slack about this.

**Comment by Sheshagiri** [comment]
will be covered in https://github.com/StackStorm/st2apidocs/pull/11

**Pull request closed without merging**
